/*
 * Bot Server API
 *
 * This is a bot API to let bots battle
 *
 * API version: 1.0.0
 * Contact: szederjesiarnold@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

// Package main sets up the dependencies and runs the program
package main

import (
	"botServer/web"
	"github.com/google/logger"
	"log"
	"net/http"
	"os"
)

func main() {
	logger.Init("Bot Server", false, true, os.Stdout)
	logger.Infof("Server started")

	ConnectAPIService := web.NewConnectAPIService()
	ConnectAPIController := web.NewConnectAPIController(ConnectAPIService)

	PlayAPIService := web.NewPlayAPIService()
	PlayAPIController := web.NewPlayAPIController(PlayAPIService)

	router := web.NewRouter(ConnectAPIController, PlayAPIController)

	log.Fatal(http.ListenAndServe(":8080", router))
}
