/*
 * Bot Server API
 *
 * This is a bot API to let bots battle
 *
 * API version: 1.0.0
 * Contact: szederjesiarnold@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

// Package main sets up the dependencies and runs the program
package main

import (
	"botServer/core"
	"botServer/web"
	"github.com/google/logger"
	"log"
	"net/http"
	"os"
	"strconv"
)

func main() {
	logger.Init("Bot Server", false, false, os.Stdout)
	logger.Infof("Server started")
	port, err := strconv.Atoi(os.Getenv("PORT"))
	if err != nil {
		logger.Infof("Could not get port from env variables, falling back to 8080")
		port = 8080
	}

	ConnectAPIService := web.NewConnectAPIService()
	ConnectAPIController := web.NewConnectAPIController(ConnectAPIService)

	PlayAPIService := web.NewPlayAPIService()
	PlayAPIController := web.NewPlayAPIController(PlayAPIService)

	router := web.NewRouter(ConnectAPIController, PlayAPIController)

	core.StartCleaner()
	log.Fatal(http.ListenAndServe(":"+strconv.Itoa(port), router))
}
