/*
 * Bot Server API
 *
 * This is a bot API to let bots battle
 *
 * API version: 1.0.0
 * Contact: szederjesiarnold@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

// Package model contains the data for web communication
package model

// Error represents a payload that is sent to the client when something goes wrong
type Error struct {
	Message string `json:"message,omitempty"`
}
