/*
 * Bot Server API
 *
 * This is a bot API to let bots battle
 *
 * API version: 1.0.0
 * Contact: szederjesiarnold@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// HelloRequest is the HTTP request body for posting to the hello endpoint
type HelloRequest struct {
	Game HelloRequestGame `json:"game"`
	// If name is not provided, server will assign a name
	PlayerName string `json:"playerName,omitempty"`
	// To receive notifications from server
	EventCallback string `json:"eventCallback"`
}

// HelloRequestGame describes the game in the context of the hello request
type HelloRequestGame struct {
	Name string `json:"name"`
	// Token to help players connect to the same game instance
	ConnectionToken      string `json:"connectionToken"`
	NumberOfTotalPlayers int    `json:"numberOfTotalPlayers,omitempty"`
}

// HelloResponse is the HTTP response from the hello endpoint
type HelloResponse struct {
	GameID string              `json:"gameId,omitempty"`
	Player HelloResponsePlayer `json:"player,omitempty"`
	// Number of rounds to play
	Rounds int `json:"rounds,omitempty"`
}

// HelloResponsePlayer describes a player in the context of a hello response
type HelloResponsePlayer struct {
	ID   string `json:"id,omitempty"`
	Name string `json:"name,omitempty"`
}
