/*
 * Bot Server API
 *
 * This is a bot API to let bots battle
 *
 * API version: 1.0.0
 * Contact: szederjesiarnold@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package model

// PlayRequest is the HTTP request body for the play endpoint
type PlayRequest struct {
	GameID   string `json:"gameId"`
	PlayerID string `json:"playerId"`
	Round    int    `json:"round"`
	Move     Move   `json:"move"`
}

// Move is game specific, and represents a player's move/actions
// in a specific game and round
type Move struct {
	Value string `json:"value"`
}

// PlayResponse is the HTTP response from the play endpoint
type PlayResponse struct {
	Round                int      `json:"round"`
	PlayersYetToMakeMove []string `json:"playersYetToMakeMove"`
}
