/*
 * Bot Server API
 *
 * This is a bot API to let bots battle
 *
 * API version: 1.0.0
 * Contact: szederjesiarnold@gmail.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package web

import (
	"botServer/web/model"
	"github.com/gorilla/websocket"
	"net/http"
)

// ConnectAPIRouter is the router for the connect API
type ConnectAPIRouter interface {
	HelloPost(http.ResponseWriter, *http.Request)
	SwitchToWs(http.ResponseWriter, *http.Request)
}

// PlayAPIRouter is the router for the play API
type PlayAPIRouter interface {
	PlayPost(http.ResponseWriter, *http.Request)
}

// ConnectAPIServicer resolves the requests to the connect API
type ConnectAPIServicer interface {
	HelloPost(model.HelloRequest) (model.HelloResponse, error)
	SwitchToWs(model.SwitchToWsRequest, *websocket.Conn) error
}

// PlayAPIServicer resolves the requests to the play API
type PlayAPIServicer interface {
	PlayPost(model.PlayRequest) (model.PlayResponse, error)
}
